// GOLDEN-STORE FIXTURE CREATOR — Phase 12E.4 (epoch-path variant).
//
// THIS FILE IS COPIED INTO THE v0.6.3 HISTORICAL WORKTREE BY
// tools/make-golden-fixtures.sh AND RUN THERE, so the store it creates is
// written by HISTORICAL CODE — the fixture is real historical bytes,
// never regenerated by the current encoder.
//
// EPOCH-PATH VARIANT: writes through the epoch writeback path
// (`epoch_create` + `epoch_write`), so the fixture carries that era's
// signature MUTATION_LOG incompat bit; a checkpoint + durability barrier
// leave it cleanly committed (no pending log tail). A runtime `if` cannot
// span eras — pre-epoch crates (v0.3.0 / v0.5.2) have no `epoch_create`
// to compile — so the eras use compile-time-distinct variants of this
// file (the tx-path variant lives in tools/golden-fixture-test.rs).
//
// The logical corpus is IDENTICAL across eras (deterministic generation,
// no RNG), so the same materialized hashes must hold in every era: the
// encoders may differ, the BYTES must not.

#![forbid(unsafe_code)]

use crate::optimizer::foreground::ForegroundPolicy;
use crate::optimizer::policy::OptimizeOptions;
use crate::store::transaction::CrashHooks;
use crate::store::{NewEntry, Store, StoreConfig};

/// Hex of a byte slice (local: no dependency assumptions across eras).
fn hex(b: &[u8]) -> String {
    let mut s = String::with_capacity(b.len() * 2);
    for byte in b {
        s.push_str(&format!("{byte:02x}"));
    }
    s
}

#[test]
fn golden_fixture() {
    let out = std::path::PathBuf::from(std::env::var("GOLDEN_OUT").expect("GOLDEN_OUT"));
    let era = std::env::var("GOLDEN_ERA").expect("GOLDEN_ERA");
    let dir = out.join(&era).join("store");
    let _ = std::fs::remove_dir_all(&dir);
    let _ = std::fs::remove_dir_all(out.join(&era));
    std::fs::create_dir_all(&dir).unwrap();

    let cfg = StoreConfig::default();
    let store = Store::create(&dir, &cfg, [0x6E; 16]).unwrap();

    // ---- corpus (identical logical bytes in every era) ----
    let hello: Vec<u8> = b"hello golden world\n".repeat(40).to_vec();
    let mut structured: Vec<u8> = Vec::new();
    for i in 0..4000u64 {
        let body = blake3::hash(&i.to_le_bytes());
        let h = hex(body.as_bytes());
        structured.extend_from_slice(
            format!("rec-{i:04} key={} value={} note=golden\n", i % 9, &h[..32]).as_bytes(),
        );
    }
    let mut random: Vec<u8> = Vec::with_capacity(65537);
    let mut seed = blake3::hash(b"entropyfs-golden-random").as_bytes().to_vec();
    while random.len() < 65537 {
        let d = blake3::hash(&seed);
        random.extend_from_slice(d.as_bytes());
        seed = d.as_bytes().to_vec();
    }
    random.truncate(65537);

    // ---- write through THIS ERA's real commit path (epoch path) ----
    let hello_ino = store
        .epoch_create(
            1,
            b"hello.txt",
            NewEntry::file(0o644, 1000, 1000),
            &CrashHooks::none(),
        )
        .unwrap();
    store
        .epoch_write(
            hello_ino,
            0,
            &hello,
            OptimizeOptions::default(),
            ForegroundPolicy::full(),
            &CrashHooks::none(),
        )
        .unwrap();
    let structured_ino = store
        .epoch_create(
            1,
            b"structured.dat",
            NewEntry::file(0o644, 1000, 1000),
            &CrashHooks::none(),
        )
        .unwrap();
    store
        .epoch_write(
            structured_ino,
            0,
            &structured,
            OptimizeOptions::default(),
            ForegroundPolicy::full(),
            &CrashHooks::none(),
        )
        .unwrap();
    let random_ino = store
        .epoch_create(
            1,
            b"random.bin",
            NewEntry::file(0o644, 1000, 1000),
            &CrashHooks::none(),
        )
        .unwrap();
    store
        .epoch_write(
            random_ino,
            0,
            &random,
            OptimizeOptions::default(),
            ForegroundPolicy::full(),
            &CrashHooks::none(),
        )
        .unwrap();
    store.epoch_checkpoint(&CrashHooks::none()).unwrap();
    store.durability_barrier(&CrashHooks::none()).unwrap();

    // ---- manifest ----
    let root = store.current_root();
    let mut m = String::new();
    m.push_str("# entropyfs golden-store fixture manifest (Phase 12E.4)\n");
    m.push_str(&format!("era = {era}\n"));
    m.push_str(&format!(
        "creator_version = {}\n",
        env!("CARGO_PKG_VERSION")
    ));
    m.push_str(&format!("format_major = {}\n", root.format_major));
    m.push_str(&format!("format_minor = {}\n", root.format_minor));
    m.push_str(&format!("incompat = 0x{:016x}\n", store.features_in_use()));
    m.push_str("ro_compat = 0x0000000000000000\n");
    m.push_str("compat = 0x0000000000000000\n");
    for (name, bytes) in [
        ("hello.txt", &hello),
        ("structured.dat", &structured),
        ("random.bin", &random),
    ] {
        let h = hex(blake3::hash(bytes).as_bytes());
        m.push_str(&format!("file = {name} {} {h}\n", bytes.len()));
    }
    std::fs::write(out.join(&era).join("manifest.txt"), m).unwrap();
    drop(store);
}
