#!/usr/bin/env bash
# Phase 12E.4: build the historical golden-store fixtures.
#
# For each era tag, this:
#   1. checks out the tag into a disposable worktree,
#   2. copies tools/golden-fixture-test.rs in as a test of THAT era,
#   3. builds and runs the historical test binary (the store is written
#      by HISTORICAL CODE — real historical bytes, never regenerated by
#      the current encoder),
#   4. copies store + manifest into testdata/golden/<era>/,
#   5. appends the creator git revision and the immutable store-dir hash,
#   6. removes the worktree.
#
# Eras (each a meaningful on-disk-format generation within format v1):
#   v0.3.0  pre-SequenceSharedDict / pre-SequenceDeep / pre-MutationLog
#   v0.5.2  pre-MutationLog final form (all sequence families)
#   v0.6.3  MutationLog (epoch writeback) era
#
# A fixture must NEVER be regenerated with the current encoder; if a
# fixture is ever lost, recreate it from its era tag with THIS script and
# review the diff.

set -euo pipefail
REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT="${GOLDEN_OUT:-/tmp/efs-golden-out}"
TEST_SRC="$REPO_ROOT/tools/golden-fixture-test.rs"

make_era() {
    local era="$1" tag="$2"
    local wt="/tmp/efs-golden-$era"
    # Era-specific fixture test: the epoch-path variant is only valid in
    # the v0.6.3 era (pre-epoch crates have no `epoch_create` to compile).
    local test_src="$TEST_SRC"
    if [[ "$era" == "v0.6.3" ]]; then
        test_src="$REPO_ROOT/tools/golden-fixture-test-epoch.rs"
    fi
    echo "== era $era ($tag) =="
    # Idempotent worktree lifecycle: a previous (possibly aborted) run can
    # leave the path registered-but-missing; prune + force-remove first so
    # `add` always succeeds.
    git -C "$REPO_ROOT" worktree remove --force "$wt" >/dev/null 2>&1 || true
    git -C "$REPO_ROOT" worktree prune
    rm -rf "$wt"
    git -C "$REPO_ROOT" worktree add --detach "$wt" "$tag" >/dev/null
    cp "$test_src" "$wt/src/tests/zz_golden_fixture.rs"
    printf '\npub mod zz_golden_fixture;\n' >> "$wt/src/tests/mod.rs"
    local rev
    rev="$(git -C "$REPO_ROOT" rev-parse "$tag")"
    (
        cd "$wt"
        GOLDEN_ERA="$era" GOLDEN_OUT="$OUT" \
            cargo test --release --lib zz_golden_fixture -- --nocapture >/dev/null 2>&1 \
            || { echo "era $era: historical build/test failed" >&2; exit 1; }
    )
    mkdir -p "$REPO_ROOT/testdata/golden/$era"
    rm -rf "$REPO_ROOT/testdata/golden/$era/store"
    cp -r "$OUT/$era/store" "$REPO_ROOT/testdata/golden/$era/store"
    cp "$OUT/$era/manifest.txt" "$REPO_ROOT/testdata/golden/$era/manifest.txt"
    printf 'creator_revision = %s\n' "$rev" >> "$REPO_ROOT/testdata/golden/$era/manifest.txt"
    # Immutable store-dir hash: BLAKE3 of the sorted per-file hash lines
    # (segments + superblock; the flock `lock` file is excluded — its
    # content is not part of the format).
    local dirhash
    dirhash="$(
        cd "$REPO_ROOT/testdata/golden/$era/store"
        find . -type f ! -name lock | sort | while read -r f; do
            blake3sum "$f" 2>/dev/null || b3sum "$f" 2>/dev/null || sha256sum "$f"
        done | blake3sum || \
        find . -type f ! -name lock | sort | while read -r f; do sha256sum "$f"; done | sha256sum
    )"
    printf 'store_dir_hash = %s\n' "$(echo "$dirhash" | cut -d' ' -f1)" >> "$REPO_ROOT/testdata/golden/$era/manifest.txt"
    git -C "$REPO_ROOT" worktree remove --force "$wt"
    echo "== era $era sealed: $(du -sh "$REPO_ROOT/testdata/golden/$era/store" | cut -f1) =="
}

make_era v0.3.0 v0.3.0
make_era v0.5.2 v0.5.2
make_era v0.6.3 v0.6.3
echo "golden fixtures: all eras sealed"
